#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#include "atlas_prefetch.h"

#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#include "atlas_prefetch.h"

#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#include "atlas_prefetch.h"

static void ATL_cJIK0x0x52TT1x1x52_aX_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=T, MB=0, NB=0, KB=52, 
 * lda=0, ldb=0, ldc=0, mu=1, nu=1, ku=52, pf=1
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.3)
 */
{
   #define Mb M
   #define Nb N
   const float *stM = A + (((lda*Mb) << 1));
   const float *stN = B + (((Nb) << 1));
   const float *pfA = A + M;
   const float BetaAlpha = beta / alpha;
   #define incAk 104
   const int incAm = ((((lda) - 52) << 1)), incAn = -(((Mb*lda) << 1));
   const int incBk = (((ldb) << 1)), incBm = -(104*(ldb));
   #define incBn 2
   #define incCm 2
   const int incCn = (((ldc) << 1)) - (((Mb) << 1));
   float *pC0=C;
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0;
   register float rB0;
   register float rC0_0;
   do /* N-loop */
   {
      ATL_pfl1R(pfA+0);
      ATL_pfl1R(pfA+16);
      ATL_pfl1R(pfA+32);
      pfA += lda;
      do /* M-loop */
      {
         rA0 = BetaAlpha;
         rC0_0 = *pC0;
         rC0_0 *= rA0;
         rA0 = *pA0;
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[2];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[4];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[6];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[8];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[10];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[12];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[14];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[16];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[18];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[20];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[22];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[24];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[26];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[28];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[30];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[32];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[34];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[36];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[38];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[40];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[42];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[44];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[46];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[48];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[50];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[52];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[54];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[56];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[58];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[60];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[62];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[64];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[66];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[68];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[70];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[72];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[74];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[76];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[78];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[80];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[82];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[84];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[86];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[88];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[90];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[92];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[94];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[96];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[98];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[100];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         rA0 = pA0[102];
         rB0 = *pB0;
         rC0_0 += rA0 * rB0;
         pB0 += incBk;
         pA0 += incAk;
         rB0 = alpha;
         rC0_0 *= rB0;
         *pC0 = rC0_0;
         pC0 += incCm;
         pA0 += incAm;
         pB0 += incBm;
      }
      while(pA0 != stM);
      pC0 += incCn;
      pA0 += incAn;
      pB0 += incBn;
   }
   while(pB0 != stN);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
static void ATL_cJIK0x0x52TT3x1x52_aX_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=T, MB=0, NB=0, KB=52, 
 * lda=0, ldb=0, ldc=0, mu=3, nu=1, ku=52, pf=1
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.3)
 */
{
   const int Mb = (M/3)*3;
   #define Nb N
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (((lda*Mb) << 1));
   const float *stN = B + (((Nb) << 1));
   const float *pfA = A + M;
   const float BetaAlpha = beta / alpha;
   #define incAk 104
   const int incAm = ((((((lda) << 1)+lda) - 52) << 1)), incAn = -(((Mb*lda) << 1));
   const int incBk = (((ldb) << 1)), incBm = -(104*(ldb));
   #define incBn 2
   #define incCm 6
   const int incCn = (((ldc) << 1)) - (((Mb) << 1));
   float *pC0=C;
   const float *pA0=A, *pA1=pA0+(((lda) << 1)), *pA2=pA1+(((lda) << 1));
   const float *pB0=B;
   register int k;
   register float rA0, rA1, rA2;
   register float rB0;
   register float rC0_0, rC1_0, rC2_0;
   if (pA0 != stM)
   {
      do /* N-loop */
      {
         ATL_pfl1R(pfA+0);
         ATL_pfl1R(pfA+16);
         ATL_pfl1R(pfA+32);
         pfA += lda;
         do /* M-loop */
         {
            rA0 = BetaAlpha;
            rC0_0 = *pC0;
            rC0_0 *= rA0;
            rC1_0 = pC0[2];
            rC1_0 *= rA0;
            rC2_0 = pC0[4];
            rC2_0 *= rA0;
            rA0 = *pA0;
            rB0 = *pB0;
            rA1 = *pA1;
            rA2 = *pA2;
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[2];
            rB0 = *pB0;
            rA1 = pA1[2];
            rA2 = pA2[2];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[4];
            rB0 = *pB0;
            rA1 = pA1[4];
            rA2 = pA2[4];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[6];
            rB0 = *pB0;
            rA1 = pA1[6];
            rA2 = pA2[6];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[8];
            rB0 = *pB0;
            rA1 = pA1[8];
            rA2 = pA2[8];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[10];
            rB0 = *pB0;
            rA1 = pA1[10];
            rA2 = pA2[10];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[12];
            rB0 = *pB0;
            rA1 = pA1[12];
            rA2 = pA2[12];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[14];
            rB0 = *pB0;
            rA1 = pA1[14];
            rA2 = pA2[14];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[16];
            rB0 = *pB0;
            rA1 = pA1[16];
            rA2 = pA2[16];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[18];
            rB0 = *pB0;
            rA1 = pA1[18];
            rA2 = pA2[18];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[20];
            rB0 = *pB0;
            rA1 = pA1[20];
            rA2 = pA2[20];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[22];
            rB0 = *pB0;
            rA1 = pA1[22];
            rA2 = pA2[22];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[24];
            rB0 = *pB0;
            rA1 = pA1[24];
            rA2 = pA2[24];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[26];
            rB0 = *pB0;
            rA1 = pA1[26];
            rA2 = pA2[26];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[28];
            rB0 = *pB0;
            rA1 = pA1[28];
            rA2 = pA2[28];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[30];
            rB0 = *pB0;
            rA1 = pA1[30];
            rA2 = pA2[30];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[32];
            rB0 = *pB0;
            rA1 = pA1[32];
            rA2 = pA2[32];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[34];
            rB0 = *pB0;
            rA1 = pA1[34];
            rA2 = pA2[34];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[36];
            rB0 = *pB0;
            rA1 = pA1[36];
            rA2 = pA2[36];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[38];
            rB0 = *pB0;
            rA1 = pA1[38];
            rA2 = pA2[38];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[40];
            rB0 = *pB0;
            rA1 = pA1[40];
            rA2 = pA2[40];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[42];
            rB0 = *pB0;
            rA1 = pA1[42];
            rA2 = pA2[42];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[44];
            rB0 = *pB0;
            rA1 = pA1[44];
            rA2 = pA2[44];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[46];
            rB0 = *pB0;
            rA1 = pA1[46];
            rA2 = pA2[46];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[48];
            rB0 = *pB0;
            rA1 = pA1[48];
            rA2 = pA2[48];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[50];
            rB0 = *pB0;
            rA1 = pA1[50];
            rA2 = pA2[50];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[52];
            rB0 = *pB0;
            rA1 = pA1[52];
            rA2 = pA2[52];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[54];
            rB0 = *pB0;
            rA1 = pA1[54];
            rA2 = pA2[54];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[56];
            rB0 = *pB0;
            rA1 = pA1[56];
            rA2 = pA2[56];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[58];
            rB0 = *pB0;
            rA1 = pA1[58];
            rA2 = pA2[58];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[60];
            rB0 = *pB0;
            rA1 = pA1[60];
            rA2 = pA2[60];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[62];
            rB0 = *pB0;
            rA1 = pA1[62];
            rA2 = pA2[62];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[64];
            rB0 = *pB0;
            rA1 = pA1[64];
            rA2 = pA2[64];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[66];
            rB0 = *pB0;
            rA1 = pA1[66];
            rA2 = pA2[66];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[68];
            rB0 = *pB0;
            rA1 = pA1[68];
            rA2 = pA2[68];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[70];
            rB0 = *pB0;
            rA1 = pA1[70];
            rA2 = pA2[70];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[72];
            rB0 = *pB0;
            rA1 = pA1[72];
            rA2 = pA2[72];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[74];
            rB0 = *pB0;
            rA1 = pA1[74];
            rA2 = pA2[74];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[76];
            rB0 = *pB0;
            rA1 = pA1[76];
            rA2 = pA2[76];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[78];
            rB0 = *pB0;
            rA1 = pA1[78];
            rA2 = pA2[78];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[80];
            rB0 = *pB0;
            rA1 = pA1[80];
            rA2 = pA2[80];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[82];
            rB0 = *pB0;
            rA1 = pA1[82];
            rA2 = pA2[82];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[84];
            rB0 = *pB0;
            rA1 = pA1[84];
            rA2 = pA2[84];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[86];
            rB0 = *pB0;
            rA1 = pA1[86];
            rA2 = pA2[86];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[88];
            rB0 = *pB0;
            rA1 = pA1[88];
            rA2 = pA2[88];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[90];
            rB0 = *pB0;
            rA1 = pA1[90];
            rA2 = pA2[90];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[92];
            rB0 = *pB0;
            rA1 = pA1[92];
            rA2 = pA2[92];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[94];
            rB0 = *pB0;
            rA1 = pA1[94];
            rA2 = pA2[94];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[96];
            rB0 = *pB0;
            rA1 = pA1[96];
            rA2 = pA2[96];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[98];
            rB0 = *pB0;
            rA1 = pA1[98];
            rA2 = pA2[98];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[100];
            rB0 = *pB0;
            rA1 = pA1[100];
            rA2 = pA2[100];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            rA0 = pA0[102];
            rB0 = *pB0;
            rA1 = pA1[102];
            rA2 = pA2[102];
            rC0_0 += rA0 * rB0;
            rC1_0 += rA1 * rB0;
            rC2_0 += rA2 * rB0;
            pB0 += incBk;
            pA0 += incAk;
            pA1 += incAk;
            pA2 += incAk;
            rB0 = alpha;
            rC0_0 *= rB0;
            rC1_0 *= rB0;
            rC2_0 *= rB0;
            *pC0 = rC0_0;
            pC0[2] = rC1_0;
            pC0[4] = rC2_0;
            pC0 += incCm;
            pA0 += incAm;
            pA1 += incAm;
            pA2 += incAm;
            pB0 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pA0 += incAn;
         pA1 += incAn;
         pA2 += incAn;
         pB0 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=M-Mb)
      ATL_cJIK0x0x52TT1x1x52_aX_bX(k, N, 52, alpha, ca + (((Mb*lda) << 1)), lda, cb, ldb, beta, cc + (((Mb) << 1)), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#include "atlas_prefetch.h"

static void ATL_cJIK0x0x52TT1x2x52_aX_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=T, MB=0, NB=0, KB=52, 
 * lda=0, ldb=0, ldc=0, mu=1, nu=2, ku=52, pf=1
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.3)
 */
{
   #define Mb M
   const int Nb = (N>>1)<<1;
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (((lda*Mb) << 1));
   const float *stN = B + (((Nb) << 1));
   const float *pfA = A + M;
   const float BetaAlpha = beta / alpha;
   #define incAk 104
   const int incAm = ((((lda) - 52) << 1)), incAn = -(((Mb*lda) << 1));
   const int incBk = (((ldb) << 1)), incBm = -(104*(ldb));
   #define incBn 4
   #define incCm 2
   const int incCn = (((ldc) << 2)) - (((Mb) << 1));
   float *pC0=C, *pC1=pC0+(((ldc) << 1));
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0;
   register float rB0, rB1;
   register float rC0_0, rC0_1;
   if (pB0 != stN)
   {
      do /* N-loop */
      {
         ATL_pfl1R(pfA+0);
         ATL_pfl1R(pfA+16);
         ATL_pfl1R(pfA+32);
         pfA += lda;
         do /* M-loop */
         {
            rA0 = BetaAlpha;
            rC0_0 = *pC0;
            rC0_0 *= rA0;
            rC0_1 = *pC1;
            rC0_1 *= rA0;
            rA0 = *pA0;
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[2];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[4];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[6];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[8];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[10];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[12];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[14];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[16];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[18];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[20];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[22];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[24];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[26];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[28];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[30];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[32];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[34];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[36];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[38];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[40];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[42];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[44];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[46];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[48];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[50];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[52];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[54];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[56];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[58];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[60];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[62];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[64];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[66];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[68];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[70];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[72];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[74];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[76];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[78];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[80];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[82];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[84];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[86];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[88];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[90];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[92];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[94];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[96];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[98];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[100];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            rA0 = pA0[102];
            rB0 = *pB0;
            rB1 = pB0[2];
            rC0_0 += rA0 * rB0;
            rC0_1 += rA0 * rB1;
            pB0 += incBk;
            pA0 += incAk;
            rB0 = alpha;
            rC0_0 *= rB0;
            rC0_1 *= rB0;
            *pC0 = rC0_0;
            *pC1 = rC0_1;
            pC0 += incCm;
            pC1 += incCm;
            pA0 += incAm;
            pB0 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pC1 += incCn;
         pA0 += incAn;
         pB0 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=N-Nb)
      ATL_cJIK0x0x52TT1x1x52_aX_bX(M, k, 52, alpha, ca, lda, cb + (((Nb) << 1)), ldb, beta, cc + (((Nb*ldc) << 1)), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
void ATL_cJIK0x0x52TT0x0x0_aX_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=T, MB=0, NB=0, KB=52, 
 * lda=0, ldb=0, ldc=0, mu=3, nu=2, ku=52, pf=1
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.3)
 */
{
   const int Mb = (M/3)*3;
   const int Nb = (N>>1)<<1;
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (((lda*Mb) << 1));
   const float *stN = B + (((Nb) << 1));
   const float *pfA = A + M;
   const float BetaAlpha = beta / alpha;
   #define incAk 104
   const int incAm = ((((((lda) << 1)+lda) - 52) << 1)), incAn = -(((Mb*lda) << 1));
   const int incBk = (((ldb) << 1)), incBm = -(104*(ldb));
   #define incBn 4
   #define incCm 6
   const int incCn = (((ldc) << 2)) - (((Mb) << 1));
   float *pC0=C, *pC1=pC0+(((ldc) << 1));
   const float *pA0=A, *pA1=pA0+(((lda) << 1)), *pA2=pA1+(((lda) << 1));
   const float *pB0=B;
   register int k;
   register float rA0, rA1, rA2;
   register float rB0, rB1;
   register float rC0_0, rC1_0, rC2_0, rC0_1, rC1_1, rC2_1;
   if (pA0 != stM)
   {
      if (pB0 != stN)
      {
         do /* N-loop */
         {
            ATL_pfl1R(pfA+0);
            ATL_pfl1R(pfA+16);
            ATL_pfl1R(pfA+32);
            pfA += lda;
            do /* M-loop */
            {
               rA0 = BetaAlpha;
               rC0_0 = *pC0;
               rC0_0 *= rA0;
               rC1_0 = pC0[2];
               rC1_0 *= rA0;
               rC2_0 = pC0[4];
               rC2_0 *= rA0;
               rC0_1 = *pC1;
               rC0_1 *= rA0;
               rC1_1 = pC1[2];
               rC1_1 *= rA0;
               rC2_1 = pC1[4];
               rC2_1 *= rA0;
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               rA2 = *pA2;
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[2];
               rB0 = *pB0;
               rA1 = pA1[2];
               rA2 = pA2[2];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[4];
               rB0 = *pB0;
               rA1 = pA1[4];
               rA2 = pA2[4];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[6];
               rB0 = *pB0;
               rA1 = pA1[6];
               rA2 = pA2[6];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[8];
               rB0 = *pB0;
               rA1 = pA1[8];
               rA2 = pA2[8];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[10];
               rB0 = *pB0;
               rA1 = pA1[10];
               rA2 = pA2[10];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[12];
               rB0 = *pB0;
               rA1 = pA1[12];
               rA2 = pA2[12];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[14];
               rB0 = *pB0;
               rA1 = pA1[14];
               rA2 = pA2[14];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[16];
               rB0 = *pB0;
               rA1 = pA1[16];
               rA2 = pA2[16];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[18];
               rB0 = *pB0;
               rA1 = pA1[18];
               rA2 = pA2[18];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[20];
               rB0 = *pB0;
               rA1 = pA1[20];
               rA2 = pA2[20];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[22];
               rB0 = *pB0;
               rA1 = pA1[22];
               rA2 = pA2[22];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[24];
               rB0 = *pB0;
               rA1 = pA1[24];
               rA2 = pA2[24];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[26];
               rB0 = *pB0;
               rA1 = pA1[26];
               rA2 = pA2[26];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[28];
               rB0 = *pB0;
               rA1 = pA1[28];
               rA2 = pA2[28];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[30];
               rB0 = *pB0;
               rA1 = pA1[30];
               rA2 = pA2[30];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[32];
               rB0 = *pB0;
               rA1 = pA1[32];
               rA2 = pA2[32];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[34];
               rB0 = *pB0;
               rA1 = pA1[34];
               rA2 = pA2[34];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[36];
               rB0 = *pB0;
               rA1 = pA1[36];
               rA2 = pA2[36];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[38];
               rB0 = *pB0;
               rA1 = pA1[38];
               rA2 = pA2[38];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[40];
               rB0 = *pB0;
               rA1 = pA1[40];
               rA2 = pA2[40];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[42];
               rB0 = *pB0;
               rA1 = pA1[42];
               rA2 = pA2[42];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[44];
               rB0 = *pB0;
               rA1 = pA1[44];
               rA2 = pA2[44];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[46];
               rB0 = *pB0;
               rA1 = pA1[46];
               rA2 = pA2[46];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[48];
               rB0 = *pB0;
               rA1 = pA1[48];
               rA2 = pA2[48];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[50];
               rB0 = *pB0;
               rA1 = pA1[50];
               rA2 = pA2[50];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[52];
               rB0 = *pB0;
               rA1 = pA1[52];
               rA2 = pA2[52];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[54];
               rB0 = *pB0;
               rA1 = pA1[54];
               rA2 = pA2[54];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[56];
               rB0 = *pB0;
               rA1 = pA1[56];
               rA2 = pA2[56];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[58];
               rB0 = *pB0;
               rA1 = pA1[58];
               rA2 = pA2[58];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[60];
               rB0 = *pB0;
               rA1 = pA1[60];
               rA2 = pA2[60];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[62];
               rB0 = *pB0;
               rA1 = pA1[62];
               rA2 = pA2[62];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[64];
               rB0 = *pB0;
               rA1 = pA1[64];
               rA2 = pA2[64];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[66];
               rB0 = *pB0;
               rA1 = pA1[66];
               rA2 = pA2[66];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[68];
               rB0 = *pB0;
               rA1 = pA1[68];
               rA2 = pA2[68];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[70];
               rB0 = *pB0;
               rA1 = pA1[70];
               rA2 = pA2[70];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[72];
               rB0 = *pB0;
               rA1 = pA1[72];
               rA2 = pA2[72];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[74];
               rB0 = *pB0;
               rA1 = pA1[74];
               rA2 = pA2[74];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[76];
               rB0 = *pB0;
               rA1 = pA1[76];
               rA2 = pA2[76];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[78];
               rB0 = *pB0;
               rA1 = pA1[78];
               rA2 = pA2[78];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[80];
               rB0 = *pB0;
               rA1 = pA1[80];
               rA2 = pA2[80];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[82];
               rB0 = *pB0;
               rA1 = pA1[82];
               rA2 = pA2[82];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[84];
               rB0 = *pB0;
               rA1 = pA1[84];
               rA2 = pA2[84];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[86];
               rB0 = *pB0;
               rA1 = pA1[86];
               rA2 = pA2[86];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[88];
               rB0 = *pB0;
               rA1 = pA1[88];
               rA2 = pA2[88];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[90];
               rB0 = *pB0;
               rA1 = pA1[90];
               rA2 = pA2[90];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[92];
               rB0 = *pB0;
               rA1 = pA1[92];
               rA2 = pA2[92];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[94];
               rB0 = *pB0;
               rA1 = pA1[94];
               rA2 = pA2[94];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[96];
               rB0 = *pB0;
               rA1 = pA1[96];
               rA2 = pA2[96];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[98];
               rB0 = *pB0;
               rA1 = pA1[98];
               rA2 = pA2[98];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[100];
               rB0 = *pB0;
               rA1 = pA1[100];
               rA2 = pA2[100];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               rA0 = pA0[102];
               rB0 = *pB0;
               rA1 = pA1[102];
               rA2 = pA2[102];
               rC0_0 += rA0 * rB0;
               rB1 = pB0[2];
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               rC0_1 += rA0 * rB1;
               rC1_1 += rA1 * rB1;
               rC2_1 += rA2 * rB1;
               pB0 += incBk;
               pA0 += incAk;
               pA1 += incAk;
               pA2 += incAk;
               rB0 = alpha;
               rC0_0 *= rB0;
               rC0_1 *= rB0;
               rC1_0 *= rB0;
               rC1_1 *= rB0;
               rC2_0 *= rB0;
               rC2_1 *= rB0;
               *pC0 = rC0_0;
               pC0[2] = rC1_0;
               pC0[4] = rC2_0;
               *pC1 = rC0_1;
               pC1[2] = rC1_1;
               pC1[4] = rC2_1;
               pC0 += incCm;
               pC1 += incCm;
               pA0 += incAm;
               pA1 += incAm;
               pA2 += incAm;
               pB0 += incBm;
            }
            while(pA0 != stM);
            pC0 += incCn;
            pC1 += incCn;
            pA0 += incAn;
            pA1 += incAn;
            pA2 += incAn;
            pB0 += incBn;
         }
         while(pB0 != stN);
      }
   }
   if (k=N-Nb)
      ATL_cJIK0x0x52TT3x1x52_aX_bX(M, k, 52, alpha, ca, lda, cb + (((Nb) << 1)), ldb, beta, cc + (((Nb*ldc) << 1)), ldc);
   if (Nb && (k=M-Mb))
      ATL_cJIK0x0x52TT1x2x52_aX_bX(k, Nb, 52, alpha, ca + (((Mb*lda) << 1)), lda, cb, ldb, beta, cc + (((Mb) << 1)), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
