#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
static void ATL_cJIK0x80x80TN1x2x24_a1_b1
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=80, KB=80, 
 * lda=80, ldb=80, ldc=0, mu=1, nu=2, ku=24, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.3)
 */
{
   #define Mb M
   const float *stM = A + (((Mb) << 6)+((Mb) << 4));
   const float *stN = B + 6400;
   #define incAk 24
   const int incAm = 0, incAn = -(((Mb) << 6)+((Mb) << 4));
   #define incBk 24
   const int incBm = -80, incBn = 160;
   const int incAk0 = ((incAk) / 24), incBk0 = ((incBk) / 24);
   #define incCm 2
   const int incCn = (((ldc) << 2)) - (((Mb) << 1));
   float *pC0=C, *pC1=pC0+(((ldc) << 1));
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0;
   register float rB0, rB1;
   register float m0, m1, m2, m3, m4, m5, m6, m7;
   register float rC0_0, rC0_1;
   do /* N-loop */
   {
      do /* M-loop */
      {
         rC0_0 = *pC0;
         rC0_1 = *pC1;
/*
 *       Start pipeline
 */
         rA0 = *pA0;
         rB0 = *pB0;
         m0 = rA0 * rB0;
         rB1 = pB0[80];
         m1 = rA0 * rB1;
         rA0 = pA0[1];
         rB0 = pB0[1];
         rB1 = pB0[81];
         m2 = rA0 * rB0;
         m3 = rA0 * rB1;
         rA0 = pA0[2];
         rB0 = pB0[2];
         rB1 = pB0[82];
         m4 = rA0 * rB0;
         m5 = rA0 * rB1;
         rA0 = pA0[3];
         rB0 = pB0[3];
         rB1 = pB0[83];
         m6 = rA0 * rB0;
         m7 = rA0 * rB1;
         rA0 = pA0[4];
         rB0 = pB0[4];
         rB1 = pB0[84];

         pA0 += (((incAk0) << 2));
         pB0 += (((incBk0) << 2));
         for (k=0; k < 72; k += 24) /* easy loop to unroll */
         {
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rC0_1 += m1;
            m1 = rA0 * rB1;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rB1 = pB0[81];
            rC0_0 += m2;
            m2 = rA0 * rB0;
            rC0_1 += m3;
            m3 = rA0 * rB1;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rB1 = pB0[82];
            rC0_0 += m4;
            m4 = rA0 * rB0;
            rC0_1 += m5;
            m5 = rA0 * rB1;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rB1 = pB0[83];
            rC0_0 += m6;
            m6 = rA0 * rB0;
            rC0_1 += m7;
            m7 = rA0 * rB1;
            rA0 = pA0[4];
            rB0 = pB0[4];
            rB1 = pB0[84];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rC0_1 += m1;
            m1 = rA0 * rB1;
            rA0 = pA0[5];
            rB0 = pB0[5];
            rB1 = pB0[85];
            rC0_0 += m2;
            m2 = rA0 * rB0;
            rC0_1 += m3;
            m3 = rA0 * rB1;
            rA0 = pA0[6];
            rB0 = pB0[6];
            rB1 = pB0[86];
            rC0_0 += m4;
            m4 = rA0 * rB0;
            rC0_1 += m5;
            m5 = rA0 * rB1;
            rA0 = pA0[7];
            rB0 = pB0[7];
            rB1 = pB0[87];
            rC0_0 += m6;
            m6 = rA0 * rB0;
            rC0_1 += m7;
            m7 = rA0 * rB1;
            rA0 = pA0[8];
            rB0 = pB0[8];
            rB1 = pB0[88];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rC0_1 += m1;
            m1 = rA0 * rB1;
            rA0 = pA0[9];
            rB0 = pB0[9];
            rB1 = pB0[89];
            rC0_0 += m2;
            m2 = rA0 * rB0;
            rC0_1 += m3;
            m3 = rA0 * rB1;
            rA0 = pA0[10];
            rB0 = pB0[10];
            rB1 = pB0[90];
            rC0_0 += m4;
            m4 = rA0 * rB0;
            rC0_1 += m5;
            m5 = rA0 * rB1;
            rA0 = pA0[11];
            rB0 = pB0[11];
            rB1 = pB0[91];
            rC0_0 += m6;
            m6 = rA0 * rB0;
            rC0_1 += m7;
            m7 = rA0 * rB1;
            rA0 = pA0[12];
            rB0 = pB0[12];
            rB1 = pB0[92];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rC0_1 += m1;
            m1 = rA0 * rB1;
            rA0 = pA0[13];
            rB0 = pB0[13];
            rB1 = pB0[93];
            rC0_0 += m2;
            m2 = rA0 * rB0;
            rC0_1 += m3;
            m3 = rA0 * rB1;
            rA0 = pA0[14];
            rB0 = pB0[14];
            rB1 = pB0[94];
            rC0_0 += m4;
            m4 = rA0 * rB0;
            rC0_1 += m5;
            m5 = rA0 * rB1;
            rA0 = pA0[15];
            rB0 = pB0[15];
            rB1 = pB0[95];
            rC0_0 += m6;
            m6 = rA0 * rB0;
            rC0_1 += m7;
            m7 = rA0 * rB1;
            rA0 = pA0[16];
            rB0 = pB0[16];
            rB1 = pB0[96];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rC0_1 += m1;
            m1 = rA0 * rB1;
            rA0 = pA0[17];
            rB0 = pB0[17];
            rB1 = pB0[97];
            rC0_0 += m2;
            m2 = rA0 * rB0;
            rC0_1 += m3;
            m3 = rA0 * rB1;
            rA0 = pA0[18];
            rB0 = pB0[18];
            rB1 = pB0[98];
            rC0_0 += m4;
            m4 = rA0 * rB0;
            rC0_1 += m5;
            m5 = rA0 * rB1;
            rA0 = pA0[19];
            rB0 = pB0[19];
            rB1 = pB0[99];
            rC0_0 += m6;
            m6 = rA0 * rB0;
            rC0_1 += m7;
            m7 = rA0 * rB1;
            rA0 = pA0[20];
            rB0 = pB0[20];
            rB1 = pB0[100];
            rC0_0 += m0;
            m0 = rA0 * rB0;
            rC0_1 += m1;
            m1 = rA0 * rB1;
            rA0 = pA0[21];
            rB0 = pB0[21];
            rB1 = pB0[101];
            rC0_0 += m2;
            m2 = rA0 * rB0;
            rC0_1 += m3;
            m3 = rA0 * rB1;
            rA0 = pA0[22];
            rB0 = pB0[22];
            rB1 = pB0[102];
            rC0_0 += m4;
            m4 = rA0 * rB0;
            rC0_1 += m5;
            m5 = rA0 * rB1;
            rA0 = pA0[23];
            rB0 = pB0[23];
            rB1 = pB0[103];
            rC0_0 += m6;
            m6 = rA0 * rB0;
            rC0_1 += m7;
            m7 = rA0 * rB1;
            rA0 = pA0[24];
            rB0 = pB0[24];
            rB1 = pB0[104];
            pA0 += incAk;
            pB0 += incBk;
         } /* end K-loop */
         rC0_0 += m0;
         m0 = rA0 * rB0;
         rC0_1 += m1;
         m1 = rA0 * rB1;
         rA0 = pA0[1];
         rB0 = pB0[1];
         rB1 = pB0[81];
         rC0_0 += m2;
         m2 = rA0 * rB0;
         rC0_1 += m3;
         m3 = rA0 * rB1;
         rA0 = pA0[2];
         rB0 = pB0[2];
         rB1 = pB0[82];
         rC0_0 += m4;
         m4 = rA0 * rB0;
         rC0_1 += m5;
         m5 = rA0 * rB1;
         rA0 = pA0[3];
         rB0 = pB0[3];
         rB1 = pB0[83];
         pA0 += (((incAk0) << 1)+incAk0);
         pB0 += (((incBk0) << 1)+incBk0);
/*
 *       Drain pipe on last iteration of K-loop
 */
         rC0_0 += m6;
         m6 = rA0 * rB0;
         rC0_1 += m7;
         m7 = rA0 * rB1;
         rC0_0 += m0;
         rC0_1 += m1;
         rC0_0 += m2;
         rC0_1 += m3;
         rC0_0 += m4;
         rC0_1 += m5;
         rC0_0 += m6;
         rC0_1 += m7;
         pA0 += incAk0;
         pB0 += incBk0;
         *pC0 = rC0_0;
         *pC1 = rC0_1;
         pC0 += incCm;
         pC1 += incCm;
         pA0 += incAm;
         pB0 += incBm;
      }
      while(pA0 != stM);
      pC0 += incCn;
      pC1 += incCn;
      pA0 += incAn;
      pB0 += incBn;
   }
   while(pB0 != stN);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
void ATL_cJIK0x80x80TN80x80x0_a1_b1
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=N, MB=0, NB=80, KB=80, 
 * lda=80, ldb=80, ldc=0, mu=3, nu=2, ku=24, pf=0
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.3)
 */
{
   const int Mb = (M/3)*3;
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (((Mb) << 6)+((Mb) << 4));
   const float *stN = B + 6400;
   #define incAk 24
   const int incAm = 160, incAn = -(((Mb) << 6)+((Mb) << 4));
   #define incBk 24
   const int incBm = -80, incBn = 160;
   const int incAk0 = ((incAk) / 24), incBk0 = ((incBk) / 24);
   #define incCm 6
   const int incCn = (((ldc) << 2)) - (((Mb) << 1));
   float *pC0=C, *pC1=pC0+(((ldc) << 1));
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0, rA1, rA2;
   register float rB0, rB1;
   register float m0, m1, m2, m3, m4, m5, m6, m7;
   register float rC0_0, rC1_0, rC2_0, rC0_1, rC1_1, rC2_1;
   if (pA0 != stM)
   {
      do /* N-loop */
      {
         do /* M-loop */
         {
            rC0_0 = *pC0;
            rC1_0 = pC0[2];
            rC2_0 = pC0[4];
            rC0_1 = *pC1;
            rC1_1 = pC1[2];
            rC2_1 = pC1[4];
/*
 *          Start pipeline
 */
            rA0 = *pA0;
            rB0 = *pB0;
            m0 = rA0 * rB0;
            rA1 = pA0[80];
            m1 = rA1 * rB0;
            rA2 = pA0[160];
            m2 = rA2 * rB0;
            rB1 = pB0[80];
            m3 = rA0 * rB1;
            m4 = rA1 * rB1;
            m5 = rA2 * rB1;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rA1 = pA0[81];
            m6 = rA0 * rB0;
            rA2 = pA0[161];
            m7 = rA1 * rB0;
            rB1 = pB0[81];

            pA0 += (incAk0);
            pB0 += (incBk0);
            for (k=0; k < 72; k += 24) /* easy loop to unroll */
            {
               rC0_0 += m0;
               m0 = rA2 * rB0;
               rC1_0 += m1;
               m1 = rA0 * rB1;
               rC2_0 += m2;
               m2 = rA1 * rB1;
               rC0_1 += m3;
               m3 = rA2 * rB1;
               rA0 = pA0[1];
               rB0 = pB0[1];
               rA1 = pA0[81];
               rC1_1 += m4;
               m4 = rA0 * rB0;
               rA2 = pA0[161];
               rC2_1 += m5;
               m5 = rA1 * rB0;
               rB1 = pB0[81];
               rC0_0 += m6;
               m6 = rA2 * rB0;
               rC1_0 += m7;
               m7 = rA0 * rB1;
               rC2_0 += m0;
               m0 = rA1 * rB1;
               rC0_1 += m1;
               m1 = rA2 * rB1;
               rA0 = pA0[2];
               rB0 = pB0[2];
               rA1 = pA0[82];
               rC1_1 += m2;
               m2 = rA0 * rB0;
               rA2 = pA0[162];
               rC2_1 += m3;
               m3 = rA1 * rB0;
               rB1 = pB0[82];
               rC0_0 += m4;
               m4 = rA2 * rB0;
               rC1_0 += m5;
               m5 = rA0 * rB1;
               rC2_0 += m6;
               m6 = rA1 * rB1;
               rC0_1 += m7;
               m7 = rA2 * rB1;
               rA0 = pA0[3];
               rB0 = pB0[3];
               rA1 = pA0[83];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rA2 = pA0[163];
               rC2_1 += m1;
               m1 = rA1 * rB0;
               rB1 = pB0[83];
               rC0_0 += m2;
               m2 = rA2 * rB0;
               rC1_0 += m3;
               m3 = rA0 * rB1;
               rC2_0 += m4;
               m4 = rA1 * rB1;
               rC0_1 += m5;
               m5 = rA2 * rB1;
               rA0 = pA0[4];
               rB0 = pB0[4];
               rA1 = pA0[84];
               rC1_1 += m6;
               m6 = rA0 * rB0;
               rA2 = pA0[164];
               rC2_1 += m7;
               m7 = rA1 * rB0;
               rB1 = pB0[84];
               rC0_0 += m0;
               m0 = rA2 * rB0;
               rC1_0 += m1;
               m1 = rA0 * rB1;
               rC2_0 += m2;
               m2 = rA1 * rB1;
               rC0_1 += m3;
               m3 = rA2 * rB1;
               rA0 = pA0[5];
               rB0 = pB0[5];
               rA1 = pA0[85];
               rC1_1 += m4;
               m4 = rA0 * rB0;
               rA2 = pA0[165];
               rC2_1 += m5;
               m5 = rA1 * rB0;
               rB1 = pB0[85];
               rC0_0 += m6;
               m6 = rA2 * rB0;
               rC1_0 += m7;
               m7 = rA0 * rB1;
               rC2_0 += m0;
               m0 = rA1 * rB1;
               rC0_1 += m1;
               m1 = rA2 * rB1;
               rA0 = pA0[6];
               rB0 = pB0[6];
               rA1 = pA0[86];
               rC1_1 += m2;
               m2 = rA0 * rB0;
               rA2 = pA0[166];
               rC2_1 += m3;
               m3 = rA1 * rB0;
               rB1 = pB0[86];
               rC0_0 += m4;
               m4 = rA2 * rB0;
               rC1_0 += m5;
               m5 = rA0 * rB1;
               rC2_0 += m6;
               m6 = rA1 * rB1;
               rC0_1 += m7;
               m7 = rA2 * rB1;
               rA0 = pA0[7];
               rB0 = pB0[7];
               rA1 = pA0[87];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rA2 = pA0[167];
               rC2_1 += m1;
               m1 = rA1 * rB0;
               rB1 = pB0[87];
               rC0_0 += m2;
               m2 = rA2 * rB0;
               rC1_0 += m3;
               m3 = rA0 * rB1;
               rC2_0 += m4;
               m4 = rA1 * rB1;
               rC0_1 += m5;
               m5 = rA2 * rB1;
               rA0 = pA0[8];
               rB0 = pB0[8];
               rA1 = pA0[88];
               rC1_1 += m6;
               m6 = rA0 * rB0;
               rA2 = pA0[168];
               rC2_1 += m7;
               m7 = rA1 * rB0;
               rB1 = pB0[88];
               rC0_0 += m0;
               m0 = rA2 * rB0;
               rC1_0 += m1;
               m1 = rA0 * rB1;
               rC2_0 += m2;
               m2 = rA1 * rB1;
               rC0_1 += m3;
               m3 = rA2 * rB1;
               rA0 = pA0[9];
               rB0 = pB0[9];
               rA1 = pA0[89];
               rC1_1 += m4;
               m4 = rA0 * rB0;
               rA2 = pA0[169];
               rC2_1 += m5;
               m5 = rA1 * rB0;
               rB1 = pB0[89];
               rC0_0 += m6;
               m6 = rA2 * rB0;
               rC1_0 += m7;
               m7 = rA0 * rB1;
               rC2_0 += m0;
               m0 = rA1 * rB1;
               rC0_1 += m1;
               m1 = rA2 * rB1;
               rA0 = pA0[10];
               rB0 = pB0[10];
               rA1 = pA0[90];
               rC1_1 += m2;
               m2 = rA0 * rB0;
               rA2 = pA0[170];
               rC2_1 += m3;
               m3 = rA1 * rB0;
               rB1 = pB0[90];
               rC0_0 += m4;
               m4 = rA2 * rB0;
               rC1_0 += m5;
               m5 = rA0 * rB1;
               rC2_0 += m6;
               m6 = rA1 * rB1;
               rC0_1 += m7;
               m7 = rA2 * rB1;
               rA0 = pA0[11];
               rB0 = pB0[11];
               rA1 = pA0[91];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rA2 = pA0[171];
               rC2_1 += m1;
               m1 = rA1 * rB0;
               rB1 = pB0[91];
               rC0_0 += m2;
               m2 = rA2 * rB0;
               rC1_0 += m3;
               m3 = rA0 * rB1;
               rC2_0 += m4;
               m4 = rA1 * rB1;
               rC0_1 += m5;
               m5 = rA2 * rB1;
               rA0 = pA0[12];
               rB0 = pB0[12];
               rA1 = pA0[92];
               rC1_1 += m6;
               m6 = rA0 * rB0;
               rA2 = pA0[172];
               rC2_1 += m7;
               m7 = rA1 * rB0;
               rB1 = pB0[92];
               rC0_0 += m0;
               m0 = rA2 * rB0;
               rC1_0 += m1;
               m1 = rA0 * rB1;
               rC2_0 += m2;
               m2 = rA1 * rB1;
               rC0_1 += m3;
               m3 = rA2 * rB1;
               rA0 = pA0[13];
               rB0 = pB0[13];
               rA1 = pA0[93];
               rC1_1 += m4;
               m4 = rA0 * rB0;
               rA2 = pA0[173];
               rC2_1 += m5;
               m5 = rA1 * rB0;
               rB1 = pB0[93];
               rC0_0 += m6;
               m6 = rA2 * rB0;
               rC1_0 += m7;
               m7 = rA0 * rB1;
               rC2_0 += m0;
               m0 = rA1 * rB1;
               rC0_1 += m1;
               m1 = rA2 * rB1;
               rA0 = pA0[14];
               rB0 = pB0[14];
               rA1 = pA0[94];
               rC1_1 += m2;
               m2 = rA0 * rB0;
               rA2 = pA0[174];
               rC2_1 += m3;
               m3 = rA1 * rB0;
               rB1 = pB0[94];
               rC0_0 += m4;
               m4 = rA2 * rB0;
               rC1_0 += m5;
               m5 = rA0 * rB1;
               rC2_0 += m6;
               m6 = rA1 * rB1;
               rC0_1 += m7;
               m7 = rA2 * rB1;
               rA0 = pA0[15];
               rB0 = pB0[15];
               rA1 = pA0[95];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rA2 = pA0[175];
               rC2_1 += m1;
               m1 = rA1 * rB0;
               rB1 = pB0[95];
               rC0_0 += m2;
               m2 = rA2 * rB0;
               rC1_0 += m3;
               m3 = rA0 * rB1;
               rC2_0 += m4;
               m4 = rA1 * rB1;
               rC0_1 += m5;
               m5 = rA2 * rB1;
               rA0 = pA0[16];
               rB0 = pB0[16];
               rA1 = pA0[96];
               rC1_1 += m6;
               m6 = rA0 * rB0;
               rA2 = pA0[176];
               rC2_1 += m7;
               m7 = rA1 * rB0;
               rB1 = pB0[96];
               rC0_0 += m0;
               m0 = rA2 * rB0;
               rC1_0 += m1;
               m1 = rA0 * rB1;
               rC2_0 += m2;
               m2 = rA1 * rB1;
               rC0_1 += m3;
               m3 = rA2 * rB1;
               rA0 = pA0[17];
               rB0 = pB0[17];
               rA1 = pA0[97];
               rC1_1 += m4;
               m4 = rA0 * rB0;
               rA2 = pA0[177];
               rC2_1 += m5;
               m5 = rA1 * rB0;
               rB1 = pB0[97];
               rC0_0 += m6;
               m6 = rA2 * rB0;
               rC1_0 += m7;
               m7 = rA0 * rB1;
               rC2_0 += m0;
               m0 = rA1 * rB1;
               rC0_1 += m1;
               m1 = rA2 * rB1;
               rA0 = pA0[18];
               rB0 = pB0[18];
               rA1 = pA0[98];
               rC1_1 += m2;
               m2 = rA0 * rB0;
               rA2 = pA0[178];
               rC2_1 += m3;
               m3 = rA1 * rB0;
               rB1 = pB0[98];
               rC0_0 += m4;
               m4 = rA2 * rB0;
               rC1_0 += m5;
               m5 = rA0 * rB1;
               rC2_0 += m6;
               m6 = rA1 * rB1;
               rC0_1 += m7;
               m7 = rA2 * rB1;
               rA0 = pA0[19];
               rB0 = pB0[19];
               rA1 = pA0[99];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rA2 = pA0[179];
               rC2_1 += m1;
               m1 = rA1 * rB0;
               rB1 = pB0[99];
               rC0_0 += m2;
               m2 = rA2 * rB0;
               rC1_0 += m3;
               m3 = rA0 * rB1;
               rC2_0 += m4;
               m4 = rA1 * rB1;
               rC0_1 += m5;
               m5 = rA2 * rB1;
               rA0 = pA0[20];
               rB0 = pB0[20];
               rA1 = pA0[100];
               rC1_1 += m6;
               m6 = rA0 * rB0;
               rA2 = pA0[180];
               rC2_1 += m7;
               m7 = rA1 * rB0;
               rB1 = pB0[100];
               rC0_0 += m0;
               m0 = rA2 * rB0;
               rC1_0 += m1;
               m1 = rA0 * rB1;
               rC2_0 += m2;
               m2 = rA1 * rB1;
               rC0_1 += m3;
               m3 = rA2 * rB1;
               rA0 = pA0[21];
               rB0 = pB0[21];
               rA1 = pA0[101];
               rC1_1 += m4;
               m4 = rA0 * rB0;
               rA2 = pA0[181];
               rC2_1 += m5;
               m5 = rA1 * rB0;
               rB1 = pB0[101];
               rC0_0 += m6;
               m6 = rA2 * rB0;
               rC1_0 += m7;
               m7 = rA0 * rB1;
               rC2_0 += m0;
               m0 = rA1 * rB1;
               rC0_1 += m1;
               m1 = rA2 * rB1;
               rA0 = pA0[22];
               rB0 = pB0[22];
               rA1 = pA0[102];
               rC1_1 += m2;
               m2 = rA0 * rB0;
               rA2 = pA0[182];
               rC2_1 += m3;
               m3 = rA1 * rB0;
               rB1 = pB0[102];
               rC0_0 += m4;
               m4 = rA2 * rB0;
               rC1_0 += m5;
               m5 = rA0 * rB1;
               rC2_0 += m6;
               m6 = rA1 * rB1;
               rC0_1 += m7;
               m7 = rA2 * rB1;
               rA0 = pA0[23];
               rB0 = pB0[23];
               rA1 = pA0[103];
               rC1_1 += m0;
               m0 = rA0 * rB0;
               rA2 = pA0[183];
               rC2_1 += m1;
               m1 = rA1 * rB0;
               rB1 = pB0[103];
               rC0_0 += m2;
               m2 = rA2 * rB0;
               rC1_0 += m3;
               m3 = rA0 * rB1;
               rC2_0 += m4;
               m4 = rA1 * rB1;
               rC0_1 += m5;
               m5 = rA2 * rB1;
               rA0 = pA0[24];
               rB0 = pB0[24];
               rA1 = pA0[104];
               rC1_1 += m6;
               m6 = rA0 * rB0;
               rA2 = pA0[184];
               rC2_1 += m7;
               m7 = rA1 * rB0;
               rB1 = pB0[104];
               pA0 += incAk;
               pB0 += incBk;
            } /* end K-loop */
            rC0_0 += m0;
            m0 = rA2 * rB0;
            rC1_0 += m1;
            m1 = rA0 * rB1;
            rC2_0 += m2;
            m2 = rA1 * rB1;
            rC0_1 += m3;
            m3 = rA2 * rB1;
            rA0 = pA0[1];
            rB0 = pB0[1];
            rA1 = pA0[81];
            rC1_1 += m4;
            m4 = rA0 * rB0;
            rA2 = pA0[161];
            rC2_1 += m5;
            m5 = rA1 * rB0;
            rB1 = pB0[81];
            rC0_0 += m6;
            m6 = rA2 * rB0;
            rC1_0 += m7;
            m7 = rA0 * rB1;
            rC2_0 += m0;
            m0 = rA1 * rB1;
            rC0_1 += m1;
            m1 = rA2 * rB1;
            rA0 = pA0[2];
            rB0 = pB0[2];
            rA1 = pA0[82];
            rC1_1 += m2;
            m2 = rA0 * rB0;
            rA2 = pA0[162];
            rC2_1 += m3;
            m3 = rA1 * rB0;
            rB1 = pB0[82];
            rC0_0 += m4;
            m4 = rA2 * rB0;
            rC1_0 += m5;
            m5 = rA0 * rB1;
            rC2_0 += m6;
            m6 = rA1 * rB1;
            rC0_1 += m7;
            m7 = rA2 * rB1;
            rA0 = pA0[3];
            rB0 = pB0[3];
            rA1 = pA0[83];
            rC1_1 += m0;
            m0 = rA0 * rB0;
            rA2 = pA0[163];
            rC2_1 += m1;
            m1 = rA1 * rB0;
            rB1 = pB0[83];
            rC0_0 += m2;
            m2 = rA2 * rB0;
            rC1_0 += m3;
            m3 = rA0 * rB1;
            rC2_0 += m4;
            m4 = rA1 * rB1;
            rC0_1 += m5;
            m5 = rA2 * rB1;
            rA0 = pA0[4];
            rB0 = pB0[4];
            rA1 = pA0[84];
            rC1_1 += m6;
            m6 = rA0 * rB0;
            rA2 = pA0[164];
            rC2_1 += m7;
            m7 = rA1 * rB0;
            rB1 = pB0[84];
            rC0_0 += m0;
            m0 = rA2 * rB0;
            rC1_0 += m1;
            m1 = rA0 * rB1;
            rC2_0 += m2;
            m2 = rA1 * rB1;
            rC0_1 += m3;
            m3 = rA2 * rB1;
            rA0 = pA0[5];
            rB0 = pB0[5];
            rA1 = pA0[85];
            rC1_1 += m4;
            m4 = rA0 * rB0;
            rA2 = pA0[165];
            rC2_1 += m5;
            m5 = rA1 * rB0;
            rB1 = pB0[85];
            rC0_0 += m6;
            m6 = rA2 * rB0;
            rC1_0 += m7;
            m7 = rA0 * rB1;
            rC2_0 += m0;
            m0 = rA1 * rB1;
            rC0_1 += m1;
            m1 = rA2 * rB1;
            rA0 = pA0[6];
            rB0 = pB0[6];
            rA1 = pA0[86];
            rC1_1 += m2;
            m2 = rA0 * rB0;
            rA2 = pA0[166];
            rC2_1 += m3;
            m3 = rA1 * rB0;
            rB1 = pB0[86];
            pA0 += (((incAk0) << 2)+((incAk0) << 1));
            pB0 += (((incBk0) << 2)+((incBk0) << 1));
/*
 *          Drain pipe on last iteration of K-loop
 */
            rC0_0 += m4;
            m4 = rA2 * rB0;
            rC1_0 += m5;
            m5 = rA0 * rB1;
            rC2_0 += m6;
            m6 = rA1 * rB1;
            rC0_1 += m7;
            m7 = rA2 * rB1;
            rC1_1 += m0;
            rC2_1 += m1;
            rC0_0 += m2;
            rC1_0 += m3;
            rC2_0 += m4;
            rC0_1 += m5;
            rC1_1 += m6;
            rC2_1 += m7;
            pA0 += incAk0;
            pB0 += incBk0;
            *pC0 = rC0_0;
            pC0[2] = rC1_0;
            pC0[4] = rC2_0;
            *pC1 = rC0_1;
            pC1[2] = rC1_1;
            pC1[4] = rC2_1;
            pC0 += incCm;
            pC1 += incCm;
            pA0 += incAm;
            pB0 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pC1 += incCn;
         pA0 += incAn;
         pB0 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=M-Mb)
      ATL_cJIK0x80x80TN1x2x24_a1_b1(k, 80, 80, alpha, ca + (((Mb) << 6)+((Mb) << 4)), lda, cb, ldb, beta, cc + (((Mb) << 1)), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
#ifdef ATL_UCLEANM
#define ATL_cpMBmm_b1 ATL_cgpMBmm_b1
#endif

void ATL_cJIK0x80x80TN80x80x0_a1_bX(const int M, const int N, const int K, const float alpha, const float *A, const int lda, const float *B, const int ldb, const float beta, float *C, const int ldc);
void ATL_cJIK0x80x80TN80x80x0_a1_bX(const int M, const int N, const int K, const float alpha, const float *A, const int lda, const float *B, const int ldb, const float beta, float *C, const int ldc);
void ATL_cJIK0x80x80TN80x80x0_a1_b1(const int M, const int N, const int K, const float alpha, const float *A, const int lda, const float *B, const int ldb, const float beta, float *C, const int ldc);

void ATL_cpMBmm_b1(const int M, const int N, const int K, const float alpha, const float *A, const int lda, const float *B, const int ldb, const float beta, float *C, const int ldc)
{
   ATL_cJIK0x80x80TN80x80x0_a1_bX(M, N, K, alpha, A, lda, B, ldb, -beta, C, ldc);
   ATL_cJIK0x80x80TN80x80x0_a1_bX(M, N, K, alpha, A, lda, B+N*ldb, ldb, beta, C+1, ldc);
   ATL_cJIK0x80x80TN80x80x0_a1_bX(M, N, K, alpha, A+M*lda, lda, B+N*ldb, ldb, -1.0, C, ldc);
   ATL_cJIK0x80x80TN80x80x0_a1_b1(M, N, K, alpha, A+M*lda, lda, B, ldb, 1.0, C+1, ldc);
}
