#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#include "atlas_prefetch.h"

#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#include "atlas_prefetch.h"

#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#include "atlas_prefetch.h"

static void ATL_cJIK0x0x0TT1x1x8_aX_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=T, MB=0, NB=0, KB=0, 
 * lda=0, ldb=0, ldc=0, mu=1, nu=1, ku=8, pf=1
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.3)
 */
{
   #define Mb M
   #define Nb N
   const int Kb = (K>>3)<<3;
   const float *stM = A + (((lda*Mb) << 1));
   const float *stN = B + (((Nb) << 1));
   const float *pfA = A + M;
   const float BetaAlpha = beta / alpha;
   #define incAk 16
   const int incAm = ((((lda) - Kb) << 1)), incAn = -(((Mb*lda) << 1));
   const int incBk = (((ldb) << 1)), incBm = -(((Kb*ldb) << 1));
   #define incBn 2
   #define incCm 2
   const int incCn = (((ldc) << 1)) - (((Mb) << 1));
   float *pC0=C;
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0;
   register float rB0;
   register float rC0_0;
   do /* N-loop */
   {
      ATL_pfl1R(pfA+0);
      ATL_pfl1R(pfA+16);
      pfA += lda;
      do /* M-loop */
      {
         rA0 = BetaAlpha;
         rC0_0 = *pC0;
         rC0_0 *= rA0;
         for (k=0; k < Kb; k += 8) /* easy loop to unroll */
         {
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[2];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[4];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[6];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[8];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[10];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[12];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[14];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            pA0 += incAk;
         }
         switch(k = (K-Kb))
         {
         case 1:
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            break;
         case 2:
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[2];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            break;
         case 3:
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[2];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[4];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            break;
         case 4:
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[2];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[4];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[6];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            break;
         case 5:
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[2];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[4];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[6];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[8];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            break;
         case 6:
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[2];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[4];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[6];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[8];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[10];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            break;
         case 7:
            rA0 = *pA0;
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[2];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[4];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[6];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[8];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[10];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            rA0 = pA0[12];
            rB0 = *pB0;
            rC0_0 += rA0 * rB0;
            pB0 += incBk;
            break;
         case 0: ;
         }
         pB0 -= k*incBk;
         rB0 = alpha;
         rC0_0 *= rB0;
         *pC0 = rC0_0;
         pC0 += incCm;
         pA0 += incAm;
         pB0 += incBm;
      }
      while(pA0 != stM);
      pC0 += incCn;
      pA0 += incAn;
      pB0 += incBn;
   }
   while(pB0 != stN);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
static void ATL_cJIK0x0x0TT3x1x8_aX_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=T, MB=0, NB=0, KB=0, 
 * lda=0, ldb=0, ldc=0, mu=3, nu=1, ku=8, pf=1
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.3)
 */
{
   const int Mb = (M/3)*3;
   #define Nb N
   const int Kb = (K>>3)<<3;
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (((lda*Mb) << 1));
   const float *stN = B + (((Nb) << 1));
   const float *pfA = A + M;
   const float BetaAlpha = beta / alpha;
   #define incAk 16
   const int incAm = ((((((lda) << 1)+lda) - Kb) << 1)), incAn = -(((Mb*lda) << 1));
   const int incBk = (((ldb) << 1)), incBm = -(((Kb*ldb) << 1));
   #define incBn 2
   #define incCm 6
   const int incCn = (((ldc) << 1)) - (((Mb) << 1));
   float *pC0=C;
   const float *pA0=A, *pA1=pA0+(((lda) << 1)), *pA2=pA1+(((lda) << 1));
   const float *pB0=B;
   register int k;
   register float rA0, rA1, rA2;
   register float rB0;
   register float rC0_0, rC1_0, rC2_0;
   if (pA0 != stM)
   {
      do /* N-loop */
      {
         ATL_pfl1R(pfA+0);
         ATL_pfl1R(pfA+16);
         pfA += lda;
         do /* M-loop */
         {
            rA0 = BetaAlpha;
            rC0_0 = *pC0;
            rC0_0 *= rA0;
            rC1_0 = pC0[2];
            rC1_0 *= rA0;
            rC2_0 = pC0[4];
            rC2_0 *= rA0;
            for (k=0; k < Kb; k += 8) /* easy loop to unroll */
            {
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               rA2 = *pA2;
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[2];
               rB0 = *pB0;
               rA1 = pA1[2];
               rA2 = pA2[2];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[4];
               rB0 = *pB0;
               rA1 = pA1[4];
               rA2 = pA2[4];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[6];
               rB0 = *pB0;
               rA1 = pA1[6];
               rA2 = pA2[6];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[8];
               rB0 = *pB0;
               rA1 = pA1[8];
               rA2 = pA2[8];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[10];
               rB0 = *pB0;
               rA1 = pA1[10];
               rA2 = pA2[10];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[12];
               rB0 = *pB0;
               rA1 = pA1[12];
               rA2 = pA2[12];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[14];
               rB0 = *pB0;
               rA1 = pA1[14];
               rA2 = pA2[14];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               pA0 += incAk;
               pA1 += incAk;
               pA2 += incAk;
            }
            switch(k = (K-Kb))
            {
            case 1:
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               rA2 = *pA2;
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               break;
            case 2:
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               rA2 = *pA2;
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[2];
               rB0 = *pB0;
               rA1 = pA1[2];
               rA2 = pA2[2];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               break;
            case 3:
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               rA2 = *pA2;
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[2];
               rB0 = *pB0;
               rA1 = pA1[2];
               rA2 = pA2[2];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[4];
               rB0 = *pB0;
               rA1 = pA1[4];
               rA2 = pA2[4];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               break;
            case 4:
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               rA2 = *pA2;
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[2];
               rB0 = *pB0;
               rA1 = pA1[2];
               rA2 = pA2[2];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[4];
               rB0 = *pB0;
               rA1 = pA1[4];
               rA2 = pA2[4];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[6];
               rB0 = *pB0;
               rA1 = pA1[6];
               rA2 = pA2[6];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               break;
            case 5:
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               rA2 = *pA2;
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[2];
               rB0 = *pB0;
               rA1 = pA1[2];
               rA2 = pA2[2];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[4];
               rB0 = *pB0;
               rA1 = pA1[4];
               rA2 = pA2[4];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[6];
               rB0 = *pB0;
               rA1 = pA1[6];
               rA2 = pA2[6];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[8];
               rB0 = *pB0;
               rA1 = pA1[8];
               rA2 = pA2[8];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               break;
            case 6:
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               rA2 = *pA2;
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[2];
               rB0 = *pB0;
               rA1 = pA1[2];
               rA2 = pA2[2];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[4];
               rB0 = *pB0;
               rA1 = pA1[4];
               rA2 = pA2[4];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[6];
               rB0 = *pB0;
               rA1 = pA1[6];
               rA2 = pA2[6];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[8];
               rB0 = *pB0;
               rA1 = pA1[8];
               rA2 = pA2[8];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[10];
               rB0 = *pB0;
               rA1 = pA1[10];
               rA2 = pA2[10];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               break;
            case 7:
               rA0 = *pA0;
               rB0 = *pB0;
               rA1 = *pA1;
               rA2 = *pA2;
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[2];
               rB0 = *pB0;
               rA1 = pA1[2];
               rA2 = pA2[2];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[4];
               rB0 = *pB0;
               rA1 = pA1[4];
               rA2 = pA2[4];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[6];
               rB0 = *pB0;
               rA1 = pA1[6];
               rA2 = pA2[6];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[8];
               rB0 = *pB0;
               rA1 = pA1[8];
               rA2 = pA2[8];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[10];
               rB0 = *pB0;
               rA1 = pA1[10];
               rA2 = pA2[10];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               rA0 = pA0[12];
               rB0 = *pB0;
               rA1 = pA1[12];
               rA2 = pA2[12];
               rC0_0 += rA0 * rB0;
               rC1_0 += rA1 * rB0;
               rC2_0 += rA2 * rB0;
               pB0 += incBk;
               break;
            case 0: ;
            }
            pB0 -= k*incBk;
            rB0 = alpha;
            rC0_0 *= rB0;
            rC1_0 *= rB0;
            rC2_0 *= rB0;
            *pC0 = rC0_0;
            pC0[2] = rC1_0;
            pC0[4] = rC2_0;
            pC0 += incCm;
            pA0 += incAm;
            pA1 += incAm;
            pA2 += incAm;
            pB0 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pA0 += incAn;
         pA1 += incAn;
         pA2 += incAn;
         pB0 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=M-Mb)
      ATL_cJIK0x0x0TT1x1x8_aX_bX(k, N, K, alpha, ca + (((Mb*lda) << 1)), lda, cb, ldb, beta, cc + (((Mb) << 1)), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
#ifndef ATL_RESTRICT
#if defined(__STDC_VERSION__) && (__STDC_VERSION__/100 >= 1999)
   #define ATL_RESTRICT restrict
#else
   #define ATL_RESTRICT
#endif
#endif
#include "atlas_prefetch.h"

static void ATL_cJIK0x0x0TT1x2x8_aX_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=T, MB=0, NB=0, KB=0, 
 * lda=0, ldb=0, ldc=0, mu=1, nu=2, ku=8, pf=1
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.3)
 */
{
   #define Mb M
   const int Nb = (N>>1)<<1;
   const int Kb = (K>>3)<<3;
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (((lda*Mb) << 1));
   const float *stN = B + (((Nb) << 1));
   const float *pfA = A + M;
   const float BetaAlpha = beta / alpha;
   #define incAk 16
   const int incAm = ((((lda) - Kb) << 1)), incAn = -(((Mb*lda) << 1));
   const int incBk = (((ldb) << 1)), incBm = -(((Kb*ldb) << 1));
   #define incBn 4
   #define incCm 2
   const int incCn = (((ldc) << 2)) - (((Mb) << 1));
   float *pC0=C, *pC1=pC0+(((ldc) << 1));
   const float *pA0=A;
   const float *pB0=B;
   register int k;
   register float rA0;
   register float rB0, rB1;
   register float rC0_0, rC0_1;
   if (pB0 != stN)
   {
      do /* N-loop */
      {
         ATL_pfl1R(pfA+0);
         ATL_pfl1R(pfA+16);
         pfA += lda;
         do /* M-loop */
         {
            rA0 = BetaAlpha;
            rC0_0 = *pC0;
            rC0_0 *= rA0;
            rC0_1 = *pC1;
            rC0_1 *= rA0;
            for (k=0; k < Kb; k += 8) /* easy loop to unroll */
            {
               rA0 = *pA0;
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[2];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[4];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[6];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[8];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[10];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[12];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[14];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               pA0 += incAk;
            }
            switch(k = (K-Kb))
            {
            case 1:
               rA0 = *pA0;
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               break;
            case 2:
               rA0 = *pA0;
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[2];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               break;
            case 3:
               rA0 = *pA0;
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[2];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[4];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               break;
            case 4:
               rA0 = *pA0;
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[2];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[4];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[6];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               break;
            case 5:
               rA0 = *pA0;
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[2];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[4];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[6];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[8];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               break;
            case 6:
               rA0 = *pA0;
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[2];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[4];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[6];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[8];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[10];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               break;
            case 7:
               rA0 = *pA0;
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[2];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[4];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[6];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[8];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[10];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               rA0 = pA0[12];
               rB0 = *pB0;
               rB1 = pB0[2];
               rC0_0 += rA0 * rB0;
               rC0_1 += rA0 * rB1;
               pB0 += incBk;
               break;
            case 0: ;
            }
            pB0 -= k*incBk;
            rB0 = alpha;
            rC0_0 *= rB0;
            rC0_1 *= rB0;
            *pC0 = rC0_0;
            *pC1 = rC0_1;
            pC0 += incCm;
            pC1 += incCm;
            pA0 += incAm;
            pB0 += incBm;
         }
         while(pA0 != stM);
         pC0 += incCn;
         pC1 += incCn;
         pA0 += incAn;
         pB0 += incBn;
      }
      while(pB0 != stN);
   }
   if (k=N-Nb)
      ATL_cJIK0x0x0TT1x1x8_aX_bX(M, k, K, alpha, ca, lda, cb + (((Nb) << 1)), ldb, beta, cc + (((Nb*ldc) << 1)), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
void ATL_cJIK0x0x0TT0x0x0_aX_bX
   (const int M, const int N, const int K, const float alpha, const float * ATL_RESTRICT A, const int lda, const float * ATL_RESTRICT B, const int ldb, const float beta, float * ATL_RESTRICT C, const int ldc)
/*
 * matmul with TA=T, TB=T, MB=0, NB=0, KB=0, 
 * lda=0, ldb=0, ldc=0, mu=3, nu=2, ku=8, pf=1
 * Generated by ATLAS/tune/blas/gemm/emit_mm.c (3.10.3)
 */
{
   const int Mb = (M/3)*3;
   const int Nb = (N>>1)<<1;
   const int Kb = (K>>3)<<3;
   const float *ca=A, *cb=B;
   float *cc=C;
   const float *stM = A + (((lda*Mb) << 1));
   const float *stN = B + (((Nb) << 1));
   const float *pfA = A + M;
   const float BetaAlpha = beta / alpha;
   #define incAk 16
   const int incAm = ((((((lda) << 1)+lda) - Kb) << 1)), incAn = -(((Mb*lda) << 1));
   const int incBk = (((ldb) << 1)), incBm = -(((Kb*ldb) << 1));
   #define incBn 4
   #define incCm 6
   const int incCn = (((ldc) << 2)) - (((Mb) << 1));
   float *pC0=C, *pC1=pC0+(((ldc) << 1));
   const float *pA0=A, *pA1=pA0+(((lda) << 1)), *pA2=pA1+(((lda) << 1));
   const float *pB0=B;
   register int k;
   register float rA0, rA1, rA2;
   register float rB0, rB1;
   register float rC0_0, rC1_0, rC2_0, rC0_1, rC1_1, rC2_1;
   if (pA0 != stM)
   {
      if (pB0 != stN)
      {
         do /* N-loop */
         {
            ATL_pfl1R(pfA+0);
            ATL_pfl1R(pfA+16);
            pfA += lda;
            do /* M-loop */
            {
               rA0 = BetaAlpha;
               rC0_0 = *pC0;
               rC0_0 *= rA0;
               rC1_0 = pC0[2];
               rC1_0 *= rA0;
               rC2_0 = pC0[4];
               rC2_0 *= rA0;
               rC0_1 = *pC1;
               rC0_1 *= rA0;
               rC1_1 = pC1[2];
               rC1_1 *= rA0;
               rC2_1 = pC1[4];
               rC2_1 *= rA0;
               for (k=0; k < Kb; k += 8) /* easy loop to unroll */
               {
                  rA0 = *pA0;
                  rB0 = *pB0;
                  rA1 = *pA1;
                  rA2 = *pA2;
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[2];
                  rB0 = *pB0;
                  rA1 = pA1[2];
                  rA2 = pA2[2];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[4];
                  rB0 = *pB0;
                  rA1 = pA1[4];
                  rA2 = pA2[4];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[6];
                  rB0 = *pB0;
                  rA1 = pA1[6];
                  rA2 = pA2[6];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[8];
                  rB0 = *pB0;
                  rA1 = pA1[8];
                  rA2 = pA2[8];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[10];
                  rB0 = *pB0;
                  rA1 = pA1[10];
                  rA2 = pA2[10];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[12];
                  rB0 = *pB0;
                  rA1 = pA1[12];
                  rA2 = pA2[12];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[14];
                  rB0 = *pB0;
                  rA1 = pA1[14];
                  rA2 = pA2[14];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  pA0 += incAk;
                  pA1 += incAk;
                  pA2 += incAk;
               }
               switch(k = (K-Kb))
               {
               case 1:
                  rA0 = *pA0;
                  rB0 = *pB0;
                  rA1 = *pA1;
                  rA2 = *pA2;
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  break;
               case 2:
                  rA0 = *pA0;
                  rB0 = *pB0;
                  rA1 = *pA1;
                  rA2 = *pA2;
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[2];
                  rB0 = *pB0;
                  rA1 = pA1[2];
                  rA2 = pA2[2];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  break;
               case 3:
                  rA0 = *pA0;
                  rB0 = *pB0;
                  rA1 = *pA1;
                  rA2 = *pA2;
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[2];
                  rB0 = *pB0;
                  rA1 = pA1[2];
                  rA2 = pA2[2];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[4];
                  rB0 = *pB0;
                  rA1 = pA1[4];
                  rA2 = pA2[4];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  break;
               case 4:
                  rA0 = *pA0;
                  rB0 = *pB0;
                  rA1 = *pA1;
                  rA2 = *pA2;
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[2];
                  rB0 = *pB0;
                  rA1 = pA1[2];
                  rA2 = pA2[2];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[4];
                  rB0 = *pB0;
                  rA1 = pA1[4];
                  rA2 = pA2[4];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[6];
                  rB0 = *pB0;
                  rA1 = pA1[6];
                  rA2 = pA2[6];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  break;
               case 5:
                  rA0 = *pA0;
                  rB0 = *pB0;
                  rA1 = *pA1;
                  rA2 = *pA2;
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[2];
                  rB0 = *pB0;
                  rA1 = pA1[2];
                  rA2 = pA2[2];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[4];
                  rB0 = *pB0;
                  rA1 = pA1[4];
                  rA2 = pA2[4];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[6];
                  rB0 = *pB0;
                  rA1 = pA1[6];
                  rA2 = pA2[6];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[8];
                  rB0 = *pB0;
                  rA1 = pA1[8];
                  rA2 = pA2[8];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  break;
               case 6:
                  rA0 = *pA0;
                  rB0 = *pB0;
                  rA1 = *pA1;
                  rA2 = *pA2;
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[2];
                  rB0 = *pB0;
                  rA1 = pA1[2];
                  rA2 = pA2[2];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[4];
                  rB0 = *pB0;
                  rA1 = pA1[4];
                  rA2 = pA2[4];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[6];
                  rB0 = *pB0;
                  rA1 = pA1[6];
                  rA2 = pA2[6];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[8];
                  rB0 = *pB0;
                  rA1 = pA1[8];
                  rA2 = pA2[8];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[10];
                  rB0 = *pB0;
                  rA1 = pA1[10];
                  rA2 = pA2[10];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  break;
               case 7:
                  rA0 = *pA0;
                  rB0 = *pB0;
                  rA1 = *pA1;
                  rA2 = *pA2;
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[2];
                  rB0 = *pB0;
                  rA1 = pA1[2];
                  rA2 = pA2[2];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[4];
                  rB0 = *pB0;
                  rA1 = pA1[4];
                  rA2 = pA2[4];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[6];
                  rB0 = *pB0;
                  rA1 = pA1[6];
                  rA2 = pA2[6];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[8];
                  rB0 = *pB0;
                  rA1 = pA1[8];
                  rA2 = pA2[8];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[10];
                  rB0 = *pB0;
                  rA1 = pA1[10];
                  rA2 = pA2[10];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  rA0 = pA0[12];
                  rB0 = *pB0;
                  rA1 = pA1[12];
                  rA2 = pA2[12];
                  rC0_0 += rA0 * rB0;
                  rB1 = pB0[2];
                  rC1_0 += rA1 * rB0;
                  rC2_0 += rA2 * rB0;
                  rC0_1 += rA0 * rB1;
                  rC1_1 += rA1 * rB1;
                  rC2_1 += rA2 * rB1;
                  pB0 += incBk;
                  break;
               case 0: ;
               }
               pB0 -= k*incBk;
               rB0 = alpha;
               rC0_0 *= rB0;
               rC0_1 *= rB0;
               rC1_0 *= rB0;
               rC1_1 *= rB0;
               rC2_0 *= rB0;
               rC2_1 *= rB0;
               *pC0 = rC0_0;
               pC0[2] = rC1_0;
               pC0[4] = rC2_0;
               *pC1 = rC0_1;
               pC1[2] = rC1_1;
               pC1[4] = rC2_1;
               pC0 += incCm;
               pC1 += incCm;
               pA0 += incAm;
               pA1 += incAm;
               pA2 += incAm;
               pB0 += incBm;
            }
            while(pA0 != stM);
            pC0 += incCn;
            pC1 += incCn;
            pA0 += incAn;
            pA1 += incAn;
            pA2 += incAn;
            pB0 += incBn;
         }
         while(pB0 != stN);
      }
   }
   if (k=N-Nb)
      ATL_cJIK0x0x0TT3x1x8_aX_bX(M, k, K, alpha, ca, lda, cb + (((Nb) << 1)), ldb, beta, cc + (((Nb*ldc) << 1)), ldc);
   if (Nb && (k=M-Mb))
      ATL_cJIK0x0x0TT1x2x8_aX_bX(k, Nb, K, alpha, ca + (((Mb*lda) << 1)), lda, cb, ldb, beta, cc + (((Mb) << 1)), ldc);
}
#ifdef incAm
   #undef incAm
#endif
#ifdef incAn
   #undef incAn
#endif
#ifdef incAk
   #undef incAk
#endif
#ifdef incBm
   #undef incBm
#endif
#ifdef incBn
   #undef incBn
#endif
#ifdef incBk
   #undef incBk
#endif
#ifdef incCm
   #undef incCm
#endif
#ifdef incCn
   #undef incCn
#endif
#ifdef incCk
   #undef incCk
#endif
#ifdef Mb
   #undef Mb
#endif
#ifdef Nb
   #undef Nb
#endif
#ifdef Kb
   #undef Kb
#endif
